version: "3"
services:
  rabbit:
    image: "rabbitmq:3.8-management-alpine"
    hostname: "rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: "rabbit"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs
  # mongo:
  #   image: "mongo"
  #   container_name: "mongo"
  #   environment:
  #     MONGO_DATA_DIR: /data/db
  #     MONGO_INITDB_DATABASE: youverify
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: admin
  #   volumes:
  #     - ./mongodb/data/db:/data/db
  #   ports:
  #     - 27017-27019:27017-27019
  # command: mongod --logpath=/dev/null # --quiet
  mongo-express:
    image: mongo-express
    # depends_on:
    #   - mongo
    container_name: "mongo-express"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    ports:
      - 8081:8081
networks:
  rabbitmq_nodejs:
    driver: bridge
